---
title: "SDTM Report"
date: "`r format(Sys.time(), '%Y-%m-%d %H:%M:%S')`"
output: 
  html_document:
    theme: flatly
    toc_float: true
params:
  report_data: NA
  domain_name: NA
---
```{css, echo=FALSE}
h2 {
  background-color: #334155;
  padding: 8px 12px;
  border-radius: 13px;
  color: #FFFFFF;
  font-weight: bold;
}
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(DT)
library(dplyr)
library(knitr)

df <- params$report_data
domain <- params$domain_name
```

## **1. Summary:** `r domain`  

**Total number of errors:** `r if(is.null(df)) 0 else nrow(df)` 

```{r summary-table}
if (!is.null(df) && nrow(df) > 0) {
  summary_df <- df %>%
    group_by(Rule_ID) %>%
    summarise(
      Count = n(),
      Variables = paste(unique(Variable), collapse = ", ")
    ) %>%
    arrange(desc(Count))


  knitr::kable(summary_df, format = "markdown")
} else {
  cat("### No errors were found！")
}
```

---

## **2. Detailed Issue Log**

```{r details-table}
if (!is.null(df) && nrow(df) > 0) {
  datatable(
    df,
    rownames = FALSE,
    filter = 'top',
    options = list(
      pageLength = 20,
      autoWidth = TRUE,
      dom = 'Bfrtip'
    ),
    colnames = c("Row", "Variable", "Rule ID", "Message")
  ) %>%
    formatStyle('Row', backgroundColor = '#f9f9f9')
}
```